import type { NumericParamDef } from '@trefoil/core';
import type { NumericField } from '@trefoil/store';

export const NESTING_PARAMS: readonly (NumericParamDef & { readonly field: NumericField })[] = [
  {
    id: 'copies',
    field: 'copies',
    label: 'Copies',
    kind: 'int',
    min: 1,
    max: 12,
    default: 6,
    lockable: true,
    randomize: { min: 1, max: 12 },
    group: 'Nesting',
  },
  {
    id: 'rotation',
    field: 'rotation',
    label: 'Rotation per copy',
    kind: 'angle',
    min: 0,
    max: 180,
    step: 1,
    default: 24,
    lockable: true,
    randomize: { min: 0, max: 180 },
    group: 'Nesting',
  },
  {
    id: 'fit',
    field: 'fit',
    label: 'Fit size',
    kind: 'number',
    min: -1,
    max: 1,
    step: 0.1,
    default: 0,
    lockable: true,
    randomize: { min: -0.5, max: 0.5 },
    group: 'Nesting',
  },
  {
    id: 'alpha',
    field: 'alpha',
    label: 'Transparency',
    kind: 'number',
    min: 0,
    max: 1,
    step: 0.01,
    default: 0.22,
    lockable: true,
    randomize: { min: 0, max: 1 },
    group: 'Nesting',
  },
];
